apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
  namespace: fcgames
type: Opaque
stringData:
  jwt-key: "ChaveSegredo12345671212121321341231231890"
  db-connection: "Data Source=/data/payments.db"
  rabbitmq-username: "guest"
  rabbitmq-password: "guest"
